apiVersion: v1 
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-pod
    app: nginx-demo
spec:
  selector:
    name: nginx-pod
    app: nginx-demo
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000