apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    name: nginx-app
    app: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-pod
      app: nginx-demo
  template:
    metadata:
      name: nginx-pod
      labels:
        name: nginx-pod
        app: nginx-demo
    spec:
      containers:
        - name: nginx-pod
          image: nginx
          ports:
          - containerPort: 80